### ISSUE TITLE
Resolve discrepancies in kriged areal biomass density calculations

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#202]
Areal biomass density estimates produced from the kriging analysis tend to be substantially smaller than values produced in previous implementations of this software/analysis. This discrepancy further propagates into subsequently large coefficient of variation (_CV_) estimates. This is a priority issue that is being tracked and requires further dissection of the code and accompanying integration tests since the precise source of the issue has not yet been identified. 

- [ ] Incorporate tests for support functions associated with the kriging analysis
- [ ] Incorporate tests (on mocked data) for the kriging analysis
- [ ] Identify the source of the areal biomass density calculation discrepancy and patch the bug/error

This also relates to #187 and will apply to #185 for once the Jolly-Hampton (1990) algorithm is implemented for the kriging analysis.

**Comment by leewujung** [comment]
This is being addressed in #215.

**Comment by brandynlucca** [comment]
The difference in integrated transect biomass between `echopop` and `EchoPro` is < 0.10 kmt, which is a < 0.001% difference. This differentiation can be attributed to a slightly different weight distribution (across age and length) due to `EchoPro` having a maximum age that doesn't capture all fish and a bug in how the female-specific length-weight regression is calculated (which also incorporates unsexed fish into the calculation). These differences propagate into the apportioned kriged biomass estimates. These issues have been addressed in the `kriging_analysis(...)` `Survey`-class method reflected in PR #241.

This can be closed once PR #241 is merged.
