### ISSUE TITLE
Revise theory pages

### ISSUE THREAD

**Issue by leewujung** [OSOceanAcoustics/echopop#208]
### Tasks

- [x] remove redundant TS-length conversion page
- [x] remove binning page
- [x] remove unnecessary parts in Core data structure page
- [x] add overarching description in `theory.md` to explain the general workflow, along with an image
- [x] reorder pages to be aligned with code implementation
- [x] remove index i, j in "NASC to areal number density" section
- [x] overhaul "Apportioning biological variables" page
   - There is an error in the current description of how biomass estimates are calculated from number density -- the actual weight is missing
   - There is a discrepancy between the use of $W_\ell$ and $W_{\ell, s}$ in the current description when converting from number of fish to weight
      - when calculating proportion within total weight of all samples (which combines aged and unaged fish), $W_\ell$ is used
      - when calculating proportion within total weight of only unaged fish, $W_{\ell, s}$ is used
- ~revise figures to clarify dimension of different data variables~
- [x] add glossary for data variables
- ~re-write Jolly-Hampton page and fix index problem as in acoustics to bio estimates page~ --> will add a new issue to track this.

**Important!** Check out Chu's google doc: [Additional notes to EchoPro Biomass Estimate_updated](https://docs.google.com/document/d/1ve6tJh17VVd5wc7Smzdkxv180YoBtzmF/edit#heading=h.gjdgxs)

**Comment by leewujung** [comment]
I've addressed most of the issues here. Will open a new issue to track changes needed for the Jolly-Hampton page.
