### ISSUE TITLE
Standardize the `config.yml` dataset input structure/naming

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#282]
> I think we should consider in the not very distant future, reconcile the difference between `survey_year_{YEAR}_config.yml` and the `Survey` object structure, so that the implementation becomes more straightforward. Especially since these are all under our control (i.e. there is no reason we cannot change the yaml file). Another thing I would recommend is to flatten the nested structures, either directly make the yaml more flat (so different types of data have the same number of depth), or in the code right after the yaml is read into the `Survey` object (so each attribute/dictionary for different data types has the same number of depth).

_Originally posted by @leewujung in https://github.com/OSOceanAcoustics/echopop/issues/274#issuecomment-2423021034_

- [ ] Change the names of dataset inputs included within the configuration files (i.e. match the names used within `Survey`)
- [ ] Deprecate the use of `Echopop.core.LAYER_NAME_MAP`
- [ ] Update configuration validators to reflect name and structural changes
- [ ] Determine the feasibility of flattening dataset inputs within the configuration to the same depth (this particularly affects how the biological datasets with different regions are handled...)
- [ ] Update/edit documentation detailing how data are loaded into and ingested by the `Survey`-class object
