### ISSUE TITLE
Enable multispecies data processing

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#289]
This is a consolidated list of Issues specific to features associated with broadening the scope of species that can be processed in `Echopop`. 

- [ ] Adapt configuration file for other fish TS-length models (#115)
- [ ] Standardize methods for consistent handling of species codes (#110, #163)
- [ ] Refactor functions to be run on single species (#246)
- [ ] Net selectivity that can be computed for each species, if desired (#162)
- [ ] Generalize variable names such that they are not hake-specific
