### ISSUE TITLE
Implement functions/methods for reports generation and plotting figures

### ISSUE THREAD

**Issue by brandynlucca** [OSOceanAcoustics/echopop#290]
This is a consolidated list of Issues specific to features associated with generating tabular reports and other results. The linked issues will be closed and progress track here. 

- [x] Identify figures needed by FEAT (#145)
- [x] Replicate data summary report subtotals (#92)
- [x] Add documentation for report files (#112)
- [x] Add utility plotting functions for required diagnostics (e.g. erroneous NASC values)
- [x] Create plotting functions (or a notebook)
- [x] Add functions for exporting specific analysis `pd.DataFrames` and dictionaries (e.g. optimized variogram parameters)

**Comment by brandynlucca** [comment]
The plotting function components of this are addressed by #295.

**Comment by brandynlucca** [comment]
Points `Add documentation for report files (https://github.com/OSOceanAcoustics/echopop/issues/112)` and `Add documentation for report files (https://github.com/OSOceanAcoustics/echopop/issues/112)` are currently in review via #301 and will be marked as `closed` once #301 is merged.

**Comment by brandynlucca** [comment]
Diagnostic plotting is currently in review via #304.

**Comment by brandynlucca** [comment]
This can be closed now that #304 has been merged.
